services:
  backend:
    container_name: backend
    depends_on:
      - database
      - redis
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/app/logs:rw
      - ./src:/app/src:rw
      - /app/node_modules
    env_file:
      - ./.env
    networks:
      - default

  
  database:
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - default
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - ./redis:/data
    networks:
      - default

networks:
  default:
    driver: bridge
